### ISSUE TITLE
Incorrect parsing of metadata

### ISSUE THREAD

**Issue by kynan** [OAButton/oab-chromeaddon#29]
I tried reporting [this paper](http://arc.aiaa.org/doi/abs/10.2514/6.2007-4079) via the Chrome addon on Chromium 38.0.2125.111 Built on Ubuntu 14.04, running on LinuxMint 17 (290379) (64-bit). The metadata found however was "Tissue Distribution, Gender- and Genotype-Dependent Expression of Autophagy-Related Genes in Avian Species" - which smells like a test paper...

**Comment by JosephMcArthur** [comment]
This issue was moved to OAButton/unified-extension#14
