### ISSUE TITLE
Update Webstore?

### ISSUE THREAD

**Issue by orschiro** [OAButton/oab-chromeaddon#33]
Dear all, 

Thanks for your work on this extension!

I saw that the latest version published to the Webstore is from 2014:

![image](https://cloud.githubusercontent.com/assets/170947/14632080/f19bf8c0-0616-11e6-8ee0-ad79a2849a19.png)

Are there any plans to update the extension in the Webstore to incorporate the updates since then?

Thankfully,

~Robert

**Comment by JosephMcArthur** [comment]
Yes! Hopefully you've seen updates coming more frequently now, and we've got others coming now!

**Comment by orschiro** [comment]
Thanks for the update, @JosephMcArthur!

Very appreciated. :+1: 

~Robert
